price=input('料金を入力>>')
price=int(price)
number=input('人数を入力>>')
number=int(number)
payment=price/number
payment=int(payment)
print('お支払いは'+str(payment)+'円です')
print('{}人で{}円のお支払い額ですと、1人あたり{}円となります'
			.format(number,price,payment))
